'use client';
import { useState } from 'react';
import { ArrowRight, Search, Zap, Calendar } from 'lucide-react';

const EXAMPLE_TOPICS = ['Claude API', 'AI agents', 'Gemini 2.0', 'AI coding tools', 'LLM benchmarks', 'OpenAI GPT-5'];

type Summary = { topic: string; summary: string; top_stories: { headline: string; source: string; published_at: string }[]; generated_at: string; };

export default function NewsSummarizerPage() {
  const [topic, setTopic] = useState('');
  const [result, setResult] = useState<Summary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSearch = async (t?: string) => {
    const searchTopic = t || topic;
    if (!searchTopic.trim()) return;
    setLoading(true); setError(''); setResult(null);
    try {
      const res = await fetch('/api/tools/news-summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: searchTopic }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error || 'Something went wrong.'); return; }
      setResult(data);
    } catch { setError('Network error. Please try again.'); }
    finally { setLoading(false); }
  };

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
      <div className="text-center mb-10">
        <div className="inline-flex items-center gap-2 badge-success text-xs mb-4">
          <Zap size={12} /> Free Forever
        </div>
        <h1 className="text-3xl md:text-4xl font-bold mb-3">AI News Summariser</h1>
        <p className="text-secondary">Enter any AI topic. Get a Veltix-synthesised summary of everything that happened in the last 7 days.</p>
      </div>

      <div className="flex gap-2 mb-4">
        <div className="relative flex-1">
          <Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted" />
          <input type="text" value={topic} onChange={e => setTopic(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleSearch()}
            placeholder="e.g. Claude API, AI agents, GPT-5..." className="input pl-10 py-3" />
        </div>
        <button onClick={() => handleSearch()} disabled={loading || !topic.trim()} className="btn-primary px-5 py-3 flex-shrink-0">
          {loading ? '...' : <ArrowRight size={16} />}
        </button>
      </div>

      <div className="flex flex-wrap gap-2 mb-8">
        {EXAMPLE_TOPICS.map(t => (
          <button key={t} onClick={() => { setTopic(t); handleSearch(t); }}
            className="text-xs px-3 py-1.5 rounded-full bg-surface-2 border border-border text-secondary hover:text-primary hover:border-border-bright transition-all">
            {t}
          </button>
        ))}
      </div>

      {error && <div className="p-4 rounded-xl bg-danger/10 border border-danger/20 text-danger text-sm mb-6">{error}</div>}

      {loading && (
        <div className="card">
          <div className="h-4 bg-surface-2 rounded animate-pulse mb-4 w-40" />
          <div className="space-y-2">{[...Array(5)].map((_, i) => <div key={i} className="h-3 bg-surface-2 rounded animate-pulse" style={{ width: `${60 + i * 8}%` }} />)}</div>
        </div>
      )}

      {result && (
        <div className="space-y-4">
          <div className="card-glow">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-bold text-primary">7-day summary: {result.topic}</h2>
              <div className="flex items-center gap-1 text-xs text-muted">
                <Calendar size={11} /> Last 7 days
              </div>
            </div>
            <p className="text-sm text-secondary leading-relaxed">{result.summary}</p>
          </div>

          {result.top_stories?.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-primary mb-3">Top stories</h3>
              <div className="space-y-2">
                {result.top_stories.map((story, i) => (
                  <div key={i} className="flex items-start gap-3 p-3 bg-surface rounded-lg border border-border">
                    <span className="text-muted text-xs font-bold w-4 flex-shrink-0 mt-0.5">#{i + 1}</span>
                    <div>
                      <p className="text-sm text-primary">{story.headline}</p>
                      <p className="text-xs text-muted mt-0.5">{story.source}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          <p className="text-xs text-center text-muted">Generated by Veltix · Powered by live news data</p>
        </div>
      )}
    </div>
  );
}
